server:
  port: 9000

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:/db/schema.sql
    data: classpath:/db/data.sql